// One-off: pull SQUADS + OPP out of the v1 game, merge with the v2 additions,
// emit src/data.js (sorted by year then name) for the build.
import { readFileSync, writeFileSync } from 'node:fs';
import { NEW_SQUADS, NEW_OPP } from '../src/squads-new.mjs';

const src = readFileSync(new URL('../v1/index.html', import.meta.url), 'utf8');
const grab = name => {
  const m = src.match(new RegExp(`const ${name}=\\[([\\s\\S]*?)\\n\\];`));
  if (!m) throw new Error(name + ' not found');
  return (0, eval)(`[${m[1]}]`);
};
const squads = grab('SQUADS');
const opp = grab('OPP');

const all = [...squads, ...NEW_SQUADS].sort((a, b) => a.y - b.y || a.t.localeCompare(b.t));
const dupes = new Set();
for (const s of all) {
  const k = s.t + s.y;
  if (dupes.has(k)) throw new Error('duplicate squad ' + k);
  dupes.add(k);
  for (const p of s.p) {
    if (!['GK', 'DEF', 'MID', 'FWD'].includes(p[1])) throw new Error('bad pos ' + s.t + s.y + ' ' + p[0]);
    if (typeof p[2] !== 'number' || p[2] < 70 || p[2] > 99) throw new Error('bad rating ' + s.t + s.y + ' ' + p[0]);
  }
  const gk = s.p.filter(p => p[1] === 'GK').length;
  if (gk < 1) throw new Error('no GK in ' + s.t + s.y);
}
const allOpp = [...opp, ...NEW_OPP];

const line = s => `{t:${JSON.stringify(s.t)},y:${s.y},f:${JSON.stringify(s.f)},p:[${s.p.map(p => `[${JSON.stringify(p[0])},${JSON.stringify(p[1])},${p[2]}]`).join(',')}]}`;
const out = `/* =========================================================
   DATA — ${all.length} iconic World Cup squads, ${all[0].y}–${all[all.length - 1].y}
   pos: GK / DEF / MID / FWD   rating: unofficial, 70–99
   (generated by scripts/extract.mjs — edit src/squads-new.mjs and re-run)
========================================================= */
const SQUADS=[
${all.map(line).join(',\n')}
];

const OPP=[
${allOpp.map(o => `[${JSON.stringify(o[0])},${JSON.stringify(o[1])},${o[2]}]`).join(',\n')}
];
`;
writeFileSync(new URL('../src/data.js', import.meta.url), out);
const players = all.reduce((a, s) => a + s.p.length, 0);
console.log(`src/data.js: ${all.length} squads, ${players} players, ${allOpp.length} opponents`);
