// One line of history per squad, keyed "team|year". Shown when the wheel lands.
export const LORE = {
"Uruguay|1950":"The Maracanazo: 200,000 fall silent in Rio as Ghiggia's near-post strike steals the cup from Brazil. Obdulio Varela simply refused to lose.",
"Hungary|1954":"The Mighty Magyars — 32 games unbeaten, the 6–3 at Wembley — undone in the Bern rain by a side they'd already beaten 8–3 that same tournament.",
"West Germany|1954":"The Miracle of Bern. 'Rahn schießt… TOR!' A broken country's first post-war joy, built on Fritz Walter's beloved rain.",
"Austria|1954":"Bronze medallists — and winners of the maddest match ever played, the 7–5 'Heat Battle of Lausanne' against the hosts.",
"Sweden|1958":"Host nation finalists: ageing Milan royalty Liedholm and Gren dragged Sweden all the way home, until a 17-year-old called Pelé intervened.",
"Brazil|1958":"The kid Pelé cried on Gilmar's shoulder, Garrincha twisted blood for fun, and Brazil's first cup was won an ocean from home.",
"Brazil|1962":"Pelé limped off after two games, so Garrincha decided to win the whole thing by himself. The Little Bird's tournament, forever.",
"Chile|1962":"Bronze on home soil two years after the great earthquake — via the infamous Battle of Santiago. Leonel Sánchez shared the Golden Boot.",
"England|1966":"They think it's all over — it is now. Moore's immaculate sleeves, Hurst's hat-trick, and football came home the only time it ever has.",
"Portugal|1966":"Eusébio scored four against North Korea after trailing 3–0, then wept leaving Wembley. Third place at their very first World Cup.",
"Soviet Union|1966":"Yashin in all black, Shesternyov in granite — the USSR's best-ever finish, fourth, with the Black Spider already a legend.",
"Hungary|1966":"The Magyars' last great vintage: Albert and Bene took Brazil apart 3–1 in the Goodison rain — Brazil's first defeat in 12 years of World Cups.",
"Brazil|1970":"The greatest team ever assembled. Carlos Alberto's thunder in the final, Pelé's no-look pass, and the Jules Rimet trophy kept for good.",
"Italy|1970":"Won the 'Game of the Century' 4–3 over West Germany — five goals in extra time — then ran out of legs against the immortals.",
"Peru|1970":"Didi's beautiful team, playing weeks after the Ancash earthquake — Cubillas scored five and even Brazil's defenders applauded.",
"Netherlands|1974":"Total Football arrives: the Cruyff Turn invented mid-match, Germany untouched for 14 passes in the final. Football's most beautiful loser.",
"West Germany|1974":"Breitner's penalty, Müller's swivel — the hosts beat the better team, because Beckenbauer's sides always knew exactly what mattered.",
"Poland|1974":"Lato's seven goals won the Golden Boot; the 'Water Battle of Frankfurt' drowned their final hopes. The golden generation took bronze.",
"Scotland|1974":"The only unbeaten team at the 1974 World Cup — and the only unbeaten team ever sent home after the groups. Drew with Brazil; out on goal difference.",
"Argentina|1978":"Ticker-tape blizzards in Buenos Aires and Kempes running through them, socks rolled down. Controversial, intoxicating, champions.",
"Netherlands|1978":"A second straight final, this time without Cruyff — Rensenbrink hit the post in the 90th minute of the final. Centimetres from immortality.",
"Austria|1978":"Córdoba: Krankl's late winner beat West Germany 3–2, Austria's first over the old rival in 47 years. Edi Finger's scream still plays on the radio.",
"Italy|1982":"Rossi, back from the ban, scored six in three games. Tardelli's scream is the sound of winning a World Cup. Zoff lifted it at 40.",
"Brazil|1982":"Sócrates, Zico, Falcão — the best team never to win it, undone by Rossi in the Tragedy of Sarrià. Beauty isn't always enough.",
"Poland|1982":"Boniek's hat-trick under the Camp Nou lights against Belgium; third place again while Smolarek ran defences ragged.",
"France|1982":"Seville: 3–1 up in extra time, then Schumacher's assault on Battiston went unpunished and the cruellest shootout ever played followed.",
"Algeria|1982":"Beat West Germany on day one — then watched the 'Disgrace of Gijón' send them home. FIFA changed the fixture rules because of them.",
"Northern Ireland|1982":"Seventeen-year-old Whiteside broke Pelé's record, Armstrong sank host nation Spain, and Jennings' giant hands did the rest.",
"France|1986":"Platini's last great stand: Brazil beaten in an epic Guadalajara shootout, before Germany broke French hearts again.",
"Argentina|1986":"Maradona's tournament. The Hand of God and the Goal of the Century, four minutes apart. One man carried a World Cup.",
"Denmark|1986":"Danish Dynamite: Elkjær and Laudrup hit Uruguay for six playing football from the future — then Spain hit them for five.",
"Belgium|1986":"Pfaff's saves, Ceulemans' shoulders and a 4–3 for the ages over the Soviets — Belgium's first golden generation made the semis.",
"Mexico|1986":"Hosts by accident, quarter-finalists by right — and Negrete's scissor-kick at the Azteca is still the World Cup's most beautiful goal.",
"Soviet Union|1986":"Lobanovskyi's Dynamo machine put six past Hungary and lost the game of the tournament 3–4 to Belgium. Belanov won the Ballon d'Or anyway.",
"Cameroon|1990":"Milla's corner-flag dance at 38 years old, England rattled in the quarters — Africa's arrival, and joyously so.",
"Colombia|1990":"Higuita playing sweeper, Valderrama setting the tempo — the draw with eventual champions Germany announced a new football nation.",
"Italy|1990":"Notti magiche: Schillaci's wild eyes and a host nation head over heels — until Caniggia's header and penalties in Naples.",
"West Germany|1990":"Matthäus drove an immaculate team through Italy's summer; Brehme settled a third straight final against Argentina.",
"England|1990":"Gazza's tears, Lineker's 'have a word with him', Waddle over the bar. England's most beloved near-miss.",
"Ireland|1990":"Jack Charlton's gang reached the quarters without winning a game in 90 minutes — Bonner's save, O'Leary's penalty, a nation in the streets.",
"Argentina|1990":"Goycochea saved everything except the final's last penalty. A hobbling Maradona dragged a broken squad within one kick of retaining it.",
"Brazil|1994":"Romário and Bebeto rocked the baby, Taffarel kept the faith, Baggio missed — the cup came back after 24 long years.",
"Bulgaria|1994":"Letchkov's bald header knocked out champions Germany and Stoichkov shared the Golden Boot. Bulgaria's greatest summer.",
"Romania|1994":"Hagi, the Maradona of the Carpathians, bent one in from near halfway and took Romania within penalties of the semis.",
"Italy|1994":"Roberto Baggio carried Italy to Pasadena on one hamstring, then skied the most famous penalty ever missed. Divine, still.",
"Sweden|1994":"Brolin, Dahlin and Kennet Andersson outscored everybody. Bronze medallists and the tournament's great entertainers.",
"Nigeria|1994":"The Super Eagles topped their group dancing and were two minutes from eliminating Italy — until Baggio intervened. Africa's highest-ranked side ever.",
"Saudi Arabia|1994":"Al-Owairan ran from his own half through five Belgians for the goal of the tournament — knockout football on their World Cup debut.",
"France|1998":"Zidane's two headers, a million on the Champs-Élysées — black, blanc, beur. France's first star, won at home.",
"Brazil|1998":"Ronaldo's convulsion on the morning of the final remains football's great mystery — the best player alive sleepwalking through Paris.",
"Netherlands|1998":"Bergkamp's touch-touch-finish against Argentina is the World Cup's most elegant goal. Penalties in the semi, of course.",
"Croatia|1998":"Šuker's Golden Boot and a 3–0 demolition of Germany — a seven-year-old country finished third at its first World Cup.",
"Denmark|1998":"The Laudrup brothers' farewell: Nigeria swept aside 4–1, then toe-to-toe with Brazil in a 2–3 quarter-final that deserved a final.",
"Senegal|2002":"Champions France beaten on opening night by their former colony — Diouf unplayable, Camara's golden goal in the knockouts.",
"South Korea|2002":"Hiddink's red wave: Italy golden-goaled, Spain out on penalties, a co-host in the semi-finals and 47 million people in the streets.",
"Brazil|2002":"The three R's — Ronaldo, Rivaldo, Ronaldinho — and redemption: Ronaldo's eight goals buried the ghosts of Paris.",
"Türkiye|2002":"Şükür scored after 10.8 seconds — still the fastest ever — and Rüştü's war paint guarded third place in their first cup since 1954.",
"United States|2002":"Dos a cero on Mexico, Portugal stunned — then a German handball on the line in the quarters went unseen. The US men's deepest modern run.",
"England|2006":"The golden generation's ceiling again: Rooney's red, Ronaldo's wink, and penalties. Always penalties.",
"Portugal|2006":"Figo's last stand and young Ronaldo's first — Scolari's streetwise side ground through England to reach the semis.",
"Italy|2006":"From the Calciopoli mud to gold in Berlin: Cannavaro's imperial year, Grosso's curler, Zidane's farewell head-butt. Pirlo conducted.",
"Germany|2006":"The Sommermärchen — a host nation fell back in love with itself, Klose top-scored, and only a 119th-minute Grosso goal stopped them.",
"France|2006":"Zidane at 34, walking on water all the way to the final's red mist. The greatest individual farewell tour football has seen.",
"Brazil|2006":"The most stacked teamsheet in history — Ronaldo, Adriano, Kaká, Ronaldinho — undone by Henry and their own gala pace.",
"Argentina|2006":"The 24-pass move finished by Cambiasso, Riquelme's tempo — then Pékerman blinked, and German shootout luck held.",
"Australia|2006":"The Golden Generation's only dance: Cahill's double off the bench, then a 95th-minute Totti penalty against the eventual champions. Tears.",
"Spain|2010":"Tiki-taka's coronation: 1–0 in every knockout round, Iniesta in minute 116, Casillas in tears. Total control as art form.",
"Netherlands|2010":"Sneijder's five goals and Robben's diagonals carried them to a third final — De Jong's kung-fu couldn't stop Iniesta.",
"Uruguay|2010":"Forlán's swerving strikes and Suárez's goal-line handball as national service — a first semi-final in forty years.",
"Germany|2010":"Özil, Müller and the kids hit England for four and Argentina for four more. Bronze, and the blueprint for everything that followed.",
"Ghana|2010":"One Suárez handball and one missed penalty from being Africa's first semi-finalist, on African soil. Gyan stepped up again in the shootout anyway.",
"Argentina|2014":"Messi dragged them to the final almost alone — then watched Higuaín, Palacio and destiny miss in the Maracanã.",
"Germany|2014":"The 7–1 heard around the world, then Götze's chest-and-volley in minute 113. A machine ten years in the making, finally crowned.",
"Colombia|2014":"James' chest-and-volley against Uruguay was the goal of the decade, and the whole squad danced after all six of his goals.",
"Costa Rica|2014":"Drawn with Uruguay, Italy and England — and won the group. Unbeaten in 90 minutes all tournament; Navas was a wall.",
"Netherlands|2014":"Van Gaal's 5-3-2 hit champions Spain for five in revenge, and Tim Krul came on purely for the shootout — and won it.",
"Croatia|2018":"Three straight extra-times, Mandžukić in the 109th against England — a country of four million reached a World Cup final.",
"Belgium|2018":"From 0–2 down to 3–2 against Japan, then Brazil beaten — the best team not in the final, by one Umtiti header.",
"France|2018":"Mbappé at 19 ran through Argentina like weather; Deschamps' pragmatists collected a second star with terrifying ease.",
"England|2018":"Set-pieces, Pickford's wrist, a first semi in 28 years — then Mandžukić again. It nearly came home; the songs echoed anyway.",
"Brazil|2018":"Tite's rebuild after the 7–1: Coutinho's bangers and Neymar's theatre, stopped cold by a Belgian counterpunch in the quarters.",
"Morocco|2022":"Africa's first semi-finalists: Spain and Portugal both beaten, Bounou unbeatable, every win celebrated dancing with their mothers.",
"Portugal|2022":"Ronaldo benched and Ramos hit a hat-trick in a 6–1 — then Morocco's wall. An era ended weeping in the tunnel.",
"Argentina|2022":"Messi's completed quest: from the Saudi shock to Lusail gold via the greatest final ever played — 3–3, Mbappé's hat-trick, Dibu's save.",
"France|2022":"Mbappé's hat-trick in the final deserved immortality; Giroud and Griezmann carried the rest. One Montiel penalty from back-to-back.",
"Japan|2022":"Germany beaten, Spain beaten, the group of death topped — and Mitoma's byline cutback measured in millimetres. Croatia needed penalties to escape.",
"Spain|1986":"Butragueño put four past Denmark — the Vulture's masterpiece — before the quarter-final shootout curse struck for the first time.",
"Spain|1994":"Nadal at the back, young Guardiola pulling strings — until Tassotti's unseen elbow broke Luis Enrique's nose and Spanish hearts in the quarters.",
"Spain|2002":"Casillas saved everything, two perfectly good goals were disallowed against co-hosts Korea, and Spain went home furious. The golden era was loading.",
"Portugal|2018":"Ronaldo's hat-trick against Spain, sealed with that stoppage-time free kick — one of the great one-man World Cup nights. Uruguay ended it in the last 16.",
"Uruguay|1970":"Mazurkiewicz's gloves and Cubilla's craft took the 1950 champions back to a semi-final — where only Pelé's Brazil could stop them.",
"Uruguay|2018":"Godín and Giménez conceded once in four games and Cavani's brace beat Ronaldo's Portugal — then Cavani's calf gave out against France.",
"Belgium|1994":"Preud'homme's tournament: the Yashin Award keeper repelled everything, and Belgium still fell to a penalty never given against Germany.",
"Belgium|2014":"The golden generation's first ride: four straight wins, De Bruyne and Lukaku surging past the USA in extra time, then Messi in the quarters.",
"Croatia|2014":"Modrić, Rakitić and Mandžukić deserved better than a group with Brazil and Mexico — and the Fred penalty in the opener still stings.",
"Croatia|2022":"Livaković saved three against Japan and stoned Brazil in the quarters — bronze for Modrić's last great tournament at 37.",
"Mexico|1998":"Hernández and Blanco — and the Blanco bunny-hop — lit up France before Germany's comeback in the last 16. The fifth-game curse begins to bite.",
"Mexico|2006":"Márquez and Borgetti took Argentina to extra time — until Maxi Rodríguez's chest-and-volley, one of the great World Cup goals, ended it.",
"Mexico|2014":"Ochoa's wall against Brazil, Herrera's touchline delirium — then 'No era penal': a 94th-minute Robben tumble and the fifth game slipped away again.",
"Japan|2002":"Co-hosts with a first-ever win and a first-ever group topped — Inamoto twice over — before Turkey ended the blue summer in the rain.",
"Japan|2010":"Honda's free kicks lit up South Africa and Japan won a group abroad for the first time — out on penalties to Paraguay without losing in 90 minutes.",
"Poland|1978":"Deyna's 100th cap, Boniek's arrival, Lato still running — a second round again for the golden generation's last full vintage.",
"Poland|2022":"Szczęsny saved two penalties — one from Messi — and dragged Poland out of the group for the first time since 1986.",
"Sweden|2002":"Larsson and Ljungberg topped a group containing England, Argentina and Nigeria — then golden-goal heartbreak against Senegal.",
"Sweden|2018":"No Zlatan? No problem. Granqvist's penalties and a deflected Forsberg winner took a team of parts to the quarter-finals.",
"Hungary|1962":"Albert announced himself with a share of the Golden Boot at 20, Tichy kept scoring — and the Czechs nicked the quarter-final 1–0.",
"Hungary|1982":"Kiss came off the bench for the fastest World Cup hat-trick ever in the 10–1 over El Salvador — still the record win. The group still wasn't survived.",
"Soviet Union|1958":"Yashin's first World Cup, Netto's captaincy, Simonyan's class — a playoff win over England, then hosts Sweden in the quarters.",
"Soviet Union|1970":"Shesternyov's last stand: a quarter-final lost to Uruguay's 117th-minute sucker punch, with Byshovets the tournament's quiet star.",
"South Korea|2010":"Park Ji-sung scored in a third straight World Cup and Korea reached a first knockout round on foreign soil — lost narrowly to Uruguay.",
"South Korea|2018":"Bottom of the group — but the Kazan miracle: Kim Young-gwon and Son beat champions Germany 2–0 and sent them home bottom of theirs.",
"South Korea|2022":"Hwang Hee-chan's 91st-minute winner against Portugal, Son weeping through a face mask — through to the knockouts on goals scored.",
"United States|1994":"Denim kits, indoor grass at the Silverdome, and a host-nation upset of Colombia — the tournament that planted American soccer.",
"United States|2010":"Donovan, 91st minute, against Algeria — the most replayed goal in US soccer history — to win the group at the death.",
"United States|2022":"Pulisic's gut-or-glory winner against Iran, scored mid-collision with the keeper, sent one of the youngest squads in the field through.",
"Colombia|1994":"The golden team arrived among the favourites and left in tragedy — Andrés Escobar's own goal, and his murder ten days later. Football's saddest story.",
"Colombia|2018":"Mina's towering headers kept rescuing them and Ospina nearly stole the England shootout. James limped through it all.",
"Scotland|1978":"Ally's Army promised the cup itself — lost to Peru, drew with Iran, then Gemmill scored THE goal against finalists Holland. Out on goal difference, obviously.",
"Scotland|1982":"Wark and Souness in full flow and a 5–2 over New Zealand — out on goal difference to the USSR. Again.",
"Scotland|1990":"Beaten by Costa Rica, brilliant against Sweden, a one-goal exit against Brazil — the Scottish World Cup experience in three acts.",
"England|1986":"Lineker's six goals won the Golden Boot, but the quarter-final belongs to one man's left hand — and the same man's feet, four minutes later.",
"England|1998":"Owen, 18, slalomed through Argentina for the tournament's most thrilling goal; Beckham's red card and another shootout sent England home anyway.",
"Cameroon|1982":"Unbeaten in three draws — including holding eventual champions Italy — and out on goals scored. The Indomitable Lions' first roar.",
"Cameroon|1994":"A rough summer redeemed by one immortal moment: Roger Milla, aged 42, scoring against Russia — still the oldest World Cup goal ever.",
"Cameroon|2002":"Eto'o and Mboma up top, Foé running the middle in what proved his final summer — out by a single point.",
"Nigeria|1998":"Oliseh's thunderbolt beat Spain in the great group upset of '98 — the Super Eagles topped it before Denmark caught them cold.",
"Nigeria|2014":"Enyeama's gloves and Musa's double against Messi's Argentina — a first knockout appearance in 16 years.",
"Nigeria|2018":"The kits sold out worldwide before kickoff; Musa's brace beat Iceland, and only Rojo's late volley for Argentina ended the dream.",
"Senegal|2018":"Mané's Lions beat Poland and went home unbeaten on points — eliminated on yellow cards, the only team ever out on fair play.",
"Senegal|2022":"African champions without the injured Mané — Koulibaly's captain's goal sent them through before England in the last 16.",
"Morocco|1986":"Timoumi and Bouderbala made history: the first African side to top a World Cup group, beating Portugal 3–1, felled by a late Matthäus free kick.",
"Morocco|1998":"Hadji's curler against Norway, Bassir's double against Scotland — three points and still out, eliminated in the dying seconds elsewhere.",
"Morocco|2018":"Eliminated by two 90th-minute goals in two games — the unluckiest team in Russia, with Ziyech pulling all the strings.",
"Ghana|2006":"Debutants with Essien and Appiah in full stride — the world's #2-ranked Czechs beaten 2–0 and a knockout place secured first time out.",
"Ghana|2014":"The team nobody wanted to play: 2–2 with eventual champions Germany, the plane full of cash, the Boateng–Muntari exits. Chaos and brilliance.",
"Ghana|2022":"Kudus announced himself with two against Korea in a 3–2 thriller — then fate dealt Uruguay and Suárez again. Revenge stayed out of reach."
};
