// 49 squads added in v4 — every major nation now has at least 4 squads.
// Same shape as the originals: {t, y, f, p:[[name,pos,rating]]}
export const NEW_SQUADS_V4 = [
// ---- Spain → 4
{t:"Spain",y:1986,f:"🇪🇸",p:[["Andoni Zubizarreta","GK",86],["José Antonio Camacho","DEF",84],["Antonio Maceda","DEF",81],["Andoni Goikoetxea","DEF",82],["Julio Alberto","DEF",79],["Ricardo Gallego","MID",81],["Víctor Muñoz","MID",81],["Míchel","MID",86],["Rafael Gordillo","MID",83],["Emilio Butragueño","FWD",90],["Julio Salinas","FWD",82],["Eloy","FWD",79]]},
{t:"Spain",y:1994,f:"🇪🇸",p:[["Andoni Zubizarreta","GK",87],["Albert Ferrer","DEF",81],["Abelardo","DEF",81],["Miguel Ángel Nadal","DEF",83],["Rafael Alkorta","DEF",80],["Sergi Barjuán","DEF",81],["Fernando Hierro","MID",87],["José Luis Caminero","MID",84],["Luis Enrique","MID",85],["Pep Guardiola","MID",85],["Julen Guerrero","MID",82],["Julio Salinas","FWD",80],["Jon Andoni Goikoetxea","FWD",81]]},
{t:"Spain",y:2002,f:"🇪🇸",p:[["Iker Casillas","GK",88],["Carles Puyol","DEF",84],["Fernando Hierro","DEF",86],["Iván Helguera","DEF",83],["Juanfran","DEF",78],["Xavi","MID",84],["Rubén Baraja","MID",84],["Juan Carlos Valerón","MID",85],["Gaizka Mendieta","MID",84],["Joaquín","FWD",83],["Raúl","FWD",90],["Fernando Morientes","FWD",87],["Diego Tristán","FWD",81]]},
// ---- Portugal → 4
{t:"Portugal",y:2018,f:"🇵🇹",p:[["Rui Patrício","GK",84],["Cédric Soares","DEF",80],["Pepe","DEF",85],["José Fonte","DEF",81],["Raphaël Guerreiro","DEF",82],["William Carvalho","MID",83],["João Moutinho","MID",83],["Adrien Silva","MID",79],["Bernardo Silva","MID",86],["João Mário","MID",80],["Cristiano Ronaldo","FWD",94],["Gonçalo Guedes","FWD",80],["Ricardo Quaresma","FWD",83]]},
// ---- Uruguay → 4
{t:"Uruguay",y:1970,f:"🇺🇾",p:[["Ladislao Mazurkiewicz","GK",87],["Luis Ubiña","DEF",79],["Atilio Ancheta","DEF",81],["Roberto Matosas","DEF",80],["Juan Mújica","DEF",78],["Julio Montero Castillo","MID",80],["Ildo Maneiro","MID",80],["Víctor Espárrago","MID",80],["Luis Cubilla","FWD",84],["Pedro Rocha","FWD",86],["Julio Morales","FWD",79]]},
{t:"Uruguay",y:2018,f:"🇺🇾",p:[["Fernando Muslera","GK",85],["Martín Cáceres","DEF",83],["Diego Godín","DEF",88],["José María Giménez","DEF",85],["Diego Laxalt","DEF",79],["Nahitan Nández","MID",81],["Matías Vecino","MID",81],["Rodrigo Bentancur","MID",83],["Lucas Torreira","MID",83],["Luis Suárez","FWD",90],["Edinson Cavani","FWD",90],["Cristhian Stuani","FWD",78]]},
// ---- Belgium → 4
{t:"Belgium",y:1994,f:"🇧🇪",p:[["Michel Preud'homme","GK",89],["Philippe Albert","DEF",85],["Georges Grün","DEF",80],["Michel De Wolf","DEF",78],["Rudi Smidts","DEF",77],["Lorenzo Staelens","MID",82],["Franky Van der Elst","MID",81],["Enzo Scifo","MID",88],["Marc Degryse","MID",83],["Marc Wilmots","FWD",83],["Josip Weber","FWD",79]]},
{t:"Belgium",y:2014,f:"🇧🇪",p:[["Thibaut Courtois","GK",86],["Toby Alderweireld","DEF",83],["Vincent Kompany","DEF",87],["Jan Vertonghen","DEF",84],["Axel Witsel","MID",84],["Marouane Fellaini","MID",82],["Kevin De Bruyne","MID",86],["Nacer Chadli","MID",80],["Eden Hazard","FWD",89],["Dries Mertens","FWD",83],["Divock Origi","FWD",79],["Romelu Lukaku","FWD",84]]},
// ---- Croatia → 4
{t:"Croatia",y:2014,f:"🇭🇷",p:[["Stipe Pletikosa","GK",80],["Darijo Srna","DEF",84],["Vedran Ćorluka","DEF",81],["Dejan Lovren","DEF",82],["Šime Vrsaljko","DEF",79],["Ivan Rakitić","MID",86],["Luka Modrić","MID",90],["Mateo Kovačić","MID",81],["Ivan Perišić","FWD",82],["Ivica Olić","FWD",80],["Mario Mandžukić","FWD",85],["Nikica Jelavić","FWD",79]]},
{t:"Croatia",y:2022,f:"🇭🇷",p:[["Dominik Livaković","GK",86],["Josip Juranović","DEF",82],["Dejan Lovren","DEF",81],["Joško Gvardiol","DEF",86],["Borna Sosa","DEF",80],["Marcelo Brozović","MID",85],["Luka Modrić","MID",92],["Mateo Kovačić","MID",86],["Mario Pašalić","MID",79],["Andrej Kramarić","FWD",83],["Ivan Perišić","FWD",85],["Mislav Oršić","FWD",80],["Bruno Petković","FWD",78]]},
// ---- Mexico → 4
{t:"Mexico",y:1998,f:"🇲🇽",p:[["Jorge Campos","GK",82],["Claudio Suárez","DEF",82],["Duilio Davino","DEF",79],["Salvador Carmona","DEF",79],["Pavel Pardo","MID",82],["Raúl Lara","MID",78],["Ramón Ramírez","MID",82],["Alberto García Aspe","MID",83],["Marcelino Bernal","MID",78],["Jesús Arellano","MID",79],["Luis Hernández","FWD",85],["Cuauhtémoc Blanco","FWD",85],["Ricardo Peláez","FWD",80]]},
{t:"Mexico",y:2006,f:"🇲🇽",p:[["Oswaldo Sánchez","GK",83],["Rafael Márquez","DEF",86],["Carlos Salcido","DEF",81],["Ricardo Osorio","DEF",80],["Mario Méndez","DEF",77],["Pavel Pardo","MID",83],["Gerardo Torrado","MID",81],["Zinha","MID",80],["Andrés Guardado","MID",79],["Omar Bravo","FWD",81],["Francisco Fonseca","FWD",80],["Jared Borgetti","FWD",82]]},
{t:"Mexico",y:2014,f:"🇲🇽",p:[["Guillermo Ochoa","GK",85],["Rafael Márquez","DEF",85],["Héctor Moreno","DEF",82],["Francisco Javier Rodríguez","DEF",79],["Paul Aguilar","DEF",80],["Miguel Layún","DEF",80],["Héctor Herrera","MID",84],["José Juan Vázquez","MID",79],["Andrés Guardado","MID",84],["Giovani dos Santos","FWD",83],["Oribe Peralta","FWD",81],["Javier Hernández","FWD",84]]},
// ---- Japan → 4
{t:"Japan",y:2002,f:"🇯🇵",p:[["Seigo Narazaki","GK",81],["Hidetoshi Matsuda","DEF",79],["Tsuneyasu Miyamoto","DEF",79],["Koji Nakata","DEF",78],["Alessandro Santos","DEF",79],["Junichi Inamoto","MID",82],["Kazuyuki Toda","MID",79],["Hidetoshi Nakata","MID",86],["Shinji Ono","MID",82],["Atsushi Yanagisawa","FWD",79],["Takayuki Suzuki","FWD",78],["Naohiro Takahara","FWD",79]]},
{t:"Japan",y:2010,f:"🇯🇵",p:[["Eiji Kawashima","GK",81],["Yuichi Komano","DEF",77],["Marcus Tulio Tanaka","DEF",80],["Yuji Nakazawa","DEF",81],["Yuto Nagatomo","DEF",80],["Yuki Abe","MID",79],["Makoto Hasebe","MID",81],["Yasuhito Endo","MID",82],["Daisuke Matsui","MID",80],["Keisuke Honda","FWD",84],["Shinji Okazaki","FWD",80],["Yoshito Okubo","FWD",79]]},
// ---- Poland → 4
{t:"Poland",y:1978,f:"🇵🇱",p:[["Jan Tomaszewski","GK",83],["Antoni Szymanowski","DEF",79],["Jerzy Gorgoń","DEF",80],["Władysław Żmuda","DEF",84],["Henryk Maculewicz","DEF",77],["Adam Nawałka","MID",78],["Kazimierz Deyna","MID",88],["Zbigniew Boniek","MID",86],["Grzegorz Lato","FWD",86],["Andrzej Szarmach","FWD",83],["Włodzimierz Lubański","FWD",84]]},
{t:"Poland",y:2022,f:"🇵🇱",p:[["Wojciech Szczęsny","GK",87],["Matty Cash","DEF",80],["Kamil Glik","DEF",80],["Jakub Kiwior","DEF",79],["Bartosz Bereszyński","DEF",78],["Grzegorz Krychowiak","MID",80],["Krystian Bielik","MID",77],["Piotr Zieliński","MID",84],["Sebastian Szymański","MID",78],["Przemysław Frankowski","MID",78],["Robert Lewandowski","FWD",89],["Arkadiusz Milik","FWD",81],["Karol Świderski","FWD",78]]},
// ---- Sweden → 4
{t:"Sweden",y:2002,f:"🇸🇪",p:[["Magnus Hedman","GK",81],["Olof Mellberg","DEF",83],["Johan Mjällby","DEF",81],["Teddy Lučić","DEF",78],["Erik Edman","DEF",78],["Tobias Linderoth","MID",80],["Anders Svensson","MID",81],["Fredrik Ljungberg","MID",84],["Niclas Alexandersson","MID",78],["Henrik Larsson","FWD",87],["Marcus Allbäck","FWD",79],["Mattias Jonson","FWD",77]]},
{t:"Sweden",y:2018,f:"🇸🇪",p:[["Robin Olsen","GK",82],["Mikael Lustig","DEF",78],["Victor Lindelöf","DEF",82],["Andreas Granqvist","DEF",82],["Ludwig Augustinsson","DEF",79],["Sebastian Larsson","MID",79],["Albin Ekdal","MID",78],["Viktor Claesson","MID",79],["Emil Forsberg","MID",83],["Ola Toivonen","FWD",78],["Marcus Berg","FWD",78],["John Guidetti","FWD",76]]},
// ---- Hungary → 4
{t:"Hungary",y:1962,f:"🇭🇺",p:[["Gyula Grosics","GK",84],["Sándor Mátrai","DEF",80],["Kálmán Mészöly","DEF",84],["László Sárosi","DEF",78],["Ernő Solymosi","MID",81],["Gyula Rákosi","MID",79],["János Göröcs","MID",82],["Flórián Albert","FWD",88],["Lajos Tichy","FWD",87],["Károly Sándor","FWD",81],["Máté Fenyvesi","FWD",80]]},
{t:"Hungary",y:1982,f:"🇭🇺",p:[["Ferenc Mészáros","GK",78],["Győző Martos","DEF",77],["Imre Garaba","DEF",79],["József Tóth","DEF",77],["Sándor Sallai","DEF",78],["Tibor Nyilasi","MID",86],["József Varga","MID",79],["László Fazekas","MID",82],["András Törőcsik","FWD",83],["László Kiss","FWD",79],["Gábor Pölöskei","FWD",79]]},
// ---- Soviet Union → 4
{t:"Soviet Union",y:1958,f:"🇷🇺",p:[["Lev Yashin","GK",92],["Vladimir Kesarev","DEF",77],["Konstantin Krizhevsky","DEF",78],["Boris Kuznetsov","DEF",77],["Igor Netto","MID",86],["Yuri Voinov","MID",82],["Viktor Tsarev","MID",77],["Valentin Ivanov","FWD",86],["Nikita Simonyan","FWD",85],["Anatoli Ilyin","FWD",80],["Alexander Ivanov","FWD",78]]},
{t:"Soviet Union",y:1970,f:"🇷🇺",p:[["Anzor Kavazashvili","GK",81],["Revaz Dzodzuashvili","DEF",79],["Albert Shesternyov","DEF",86],["Murtaz Khurtsilava","DEF",81],["Yevgeni Lovchev","DEF",79],["Vladimir Muntyan","MID",82],["Kakhi Asatiani","MID",79],["Viktor Serebryanikov","MID",78],["Anatoliy Byshovets","FWD",85],["Vitaly Khmelnitsky","FWD",80],["Gennady Yevryuzhikhin","FWD",78]]},
// ---- South Korea → 4
{t:"South Korea",y:2010,f:"🇰🇷",p:[["Jung Sung-ryong","GK",79],["Cha Du-ri","DEF",79],["Cho Yong-hyung","DEF",77],["Lee Jung-soo","DEF",78],["Lee Young-pyo","DEF",81],["Kim Jung-woo","MID",78],["Ki Sung-yueng","MID",80],["Park Ji-sung","MID",86],["Lee Chung-yong","MID",82],["Park Chu-young","FWD",81],["Yeom Ki-hun","FWD",77]]},
{t:"South Korea",y:2018,f:"🇰🇷",p:[["Cho Hyun-woo","GK",81],["Lee Yong","DEF",77],["Jang Hyun-soo","DEF",77],["Kim Young-gwon","DEF",80],["Hong Chul","DEF",77],["Jung Woo-young","MID",78],["Ki Sung-yueng","MID",82],["Lee Jae-sung","MID",79],["Moon Seon-min","MID",76],["Hwang Hee-chan","FWD",80],["Son Heung-min","FWD",87],["Kim Shin-wook","FWD",77]]},
{t:"South Korea",y:2022,f:"🇰🇷",p:[["Kim Seung-gyu","GK",79],["Kim Moon-hwan","DEF",77],["Kim Min-jae","DEF",85],["Kim Young-gwon","DEF",79],["Kim Jin-su","DEF",78],["Jung Woo-young","MID",77],["Hwang In-beom","MID",81],["Lee Jae-sung","MID",79],["Son Heung-min","FWD",88],["Hwang Hee-chan","FWD",82],["Cho Gue-sung","FWD",80]]},
// ---- United States → 4
{t:"United States",y:1994,f:"🇺🇸",p:[["Tony Meola","GK",80],["Alexi Lalas","DEF",79],["Marcelo Balboa","DEF",80],["Paul Caligiuri","DEF",77],["Fernando Clavijo","DEF",76],["Thomas Dooley","MID",79],["Mike Sorber","MID",77],["Tab Ramos","MID",81],["John Harkes","MID",80],["Cobi Jones","MID",79],["Eric Wynalda","FWD",81],["Earnie Stewart","FWD",80],["Roy Wegerle","FWD",78]]},
{t:"United States",y:2010,f:"🇺🇸",p:[["Tim Howard","GK",84],["Steve Cherundolo","DEF",79],["Oguchi Onyewu","DEF",79],["Jay DeMerit","DEF",77],["Carlos Bocanegra","DEF",80],["Maurice Edu","MID",78],["Michael Bradley","MID",82],["Benny Feilhaber","MID",78],["Clint Dempsey","MID",84],["Landon Donovan","FWD",85],["Jozy Altidore","FWD",80],["Herculez Gomez","FWD",76]]},
{t:"United States",y:2022,f:"🇺🇸",p:[["Matt Turner","GK",80],["Sergiño Dest","DEF",80],["Walker Zimmerman","DEF",78],["Tim Ream","DEF",79],["Antonee Robinson","DEF",80],["Tyler Adams","MID",82],["Weston McKennie","MID",82],["Yunus Musah","MID",80],["Christian Pulisic","FWD",84],["Tim Weah","FWD",80],["Josh Sargent","FWD",78],["Brenden Aaronson","MID",78]]},
// ---- Colombia → 4
{t:"Colombia",y:1994,f:"🇨🇴",p:[["Óscar Córdoba","GK",81],["Andrés Escobar","DEF",82],["Luis Fernando Herrera","DEF",78],["Alexis Mendoza","DEF",77],["Wilson Pérez","DEF",76],["Leonel Álvarez","MID",79],["Gabriel Gómez","MID",78],["Freddy Rincón","MID",85],["Carlos Valderrama","MID",89],["Faustino Asprilla","FWD",87],["Adolfo Valencia","FWD",82],["Antony de Ávila","FWD",79]]},
{t:"Colombia",y:2018,f:"🇨🇴",p:[["David Ospina","GK",84],["Santiago Arias","DEF",79],["Yerry Mina","DEF",83],["Davinson Sánchez","DEF",83],["Johan Mojica","DEF",78],["Wílmar Barrios","MID",80],["Carlos Sánchez","MID",79],["Jefferson Lerma","MID",79],["Juan Fernando Quintero","MID",82],["Juan Guillermo Cuadrado","MID",85],["James Rodríguez","MID",89],["Radamel Falcao","FWD",86]]},
// ---- Scotland → 4
{t:"Scotland",y:1978,f:"🏴󠁧󠁢󠁳󠁣󠁴󠁿",p:[["Alan Rough","GK",78],["Stuart Kennedy","DEF",77],["Willie Donachie","DEF",78],["Tom Forsyth","DEF",78],["Kenny Burns","DEF",80],["Martin Buchan","DEF",81],["Bruce Rioch","MID",80],["Don Masson","MID",78],["Graeme Souness","MID",85],["Archie Gemmill","MID",85],["Asa Hartford","MID",80],["Kenny Dalglish","FWD",88],["Joe Jordan","FWD",83]]},
{t:"Scotland",y:1982,f:"🏴󠁧󠁢󠁳󠁣󠁴󠁿",p:[["Alan Rough","GK",78],["Danny McGrain","DEF",82],["Alan Hansen","DEF",84],["Willie Miller","DEF",82],["Frank Gray","DEF",78],["Graeme Souness","MID",87],["Gordon Strachan","MID",84],["John Wark","MID",82],["John Robertson","MID",83],["Kenny Dalglish","FWD",86],["Joe Jordan","FWD",81],["Steve Archibald","FWD",80],["Alan Brazil","FWD",78]]},
{t:"Scotland",y:1990,f:"🏴󠁧󠁢󠁳󠁣󠁴󠁿",p:[["Jim Leighton","GK",81],["Richard Gough","DEF",82],["Alex McLeish","DEF",81],["Dave McPherson","DEF",78],["Maurice Malpas","DEF",79],["Roy Aitken","MID",80],["Paul McStay","MID",83],["Murdo MacLeod","MID",78],["Stuart McCall","MID",79],["Jim Bett","MID",77],["Mo Johnston","FWD",83],["Ally McCoist","FWD",82],["Gordon Durie","FWD",78]]},
// ---- England → 6
{t:"England",y:1986,f:"🏴󠁧󠁢󠁥󠁮󠁧󠁿",p:[["Peter Shilton","GK",89],["Gary Stevens","DEF",79],["Kenny Sansom","DEF",82],["Terry Butcher","DEF",84],["Terry Fenwick","DEF",78],["Glenn Hoddle","MID",87],["Bryan Robson","MID",87],["Ray Wilkins","MID",82],["Peter Reid","MID",81],["Trevor Steven","MID",81],["Chris Waddle","FWD",84],["Gary Lineker","FWD",90],["Peter Beardsley","FWD",84],["John Barnes","FWD",84]]},
{t:"England",y:1998,f:"🏴󠁧󠁢󠁥󠁮󠁧󠁿",p:[["David Seaman","GK",87],["Gary Neville","DEF",83],["Tony Adams","DEF",86],["Sol Campbell","DEF",85],["Graeme Le Saux","DEF",81],["David Beckham","MID",86],["Paul Ince","MID",84],["Paul Scholes","MID",86],["Darren Anderton","MID",80],["David Batty","MID",79],["Alan Shearer","FWD",89],["Michael Owen","FWD",85],["Teddy Sheringham","FWD",83]]},
// ---- Cameroon → 4
{t:"Cameroon",y:1982,f:"🇨🇲",p:[["Thomas N'Kono","GK",86],["René N'Djeya","DEF",77],["Elie Onana","DEF",76],["Emmanuel Kundé","DEF",78],["Michel Kaham","DEF",76],["Ibrahim Aoudou","MID",77],["Théophile Abega","MID",84],["Grégoire M'Bida","MID",80],["Jean Manga-Onguéné","FWD",82],["Roger Milla","FWD",85],["Jacques N'Guea","FWD",76]]},
{t:"Cameroon",y:1994,f:"🇨🇲",p:[["Joseph-Antoine Bell","GK",80],["Rigobert Song","DEF",76],["Stephen Tataw","DEF",76],["Raymond Kalla","DEF",77],["Hans Agbo","DEF",75],["Marc-Vivien Foé","MID",82],["Emile Mbouh","MID",78],["Louis-Paul Mfede","MID",77],["François Omam-Biyik","FWD",83],["Roger Milla","FWD",80],["David Embé","FWD",76],["Alphonse Tchami","FWD",77]]},
{t:"Cameroon",y:2002,f:"🇨🇲",p:[["Boukar Alioum","GK",78],["Rigobert Song","DEF",82],["Raymond Kalla","DEF",79],["Pierre Wome","DEF",79],["Bill Tchato","DEF",77],["Geremi","MID",82],["Lauren","MID",82],["Marc-Vivien Foé","MID",84],["Salomon Olembé","MID",79],["Eric Djemba-Djemba","MID",78],["Patrick Mboma","FWD",84],["Samuel Eto'o","FWD",85]]},
// ---- Nigeria → 4
{t:"Nigeria",y:1998,f:"🇳🇬",p:[["Peter Rufai","GK",81],["Taribo West","DEF",80],["Uche Okechukwu","DEF",80],["Celestine Babayaro","DEF",80],["Augustine Eguavoen","DEF",77],["Sunday Oliseh","MID",84],["Jay-Jay Okocha","MID",89],["Finidi George","MID",83],["Garba Lawal","MID",78],["Nwankwo Kanu","FWD",84],["Victor Ikpeba","FWD",81],["Daniel Amokachi","FWD",81],["Tijani Babangida","FWD",79]]},
{t:"Nigeria",y:2014,f:"🇳🇬",p:[["Vincent Enyeama","GK",84],["Efe Ambrose","DEF",78],["Joseph Yobo","DEF",81],["Kenneth Omeruo","DEF",78],["Juwon Oshaniwa","DEF",76],["Ogenyi Onazi","MID",78],["John Obi Mikel","MID",82],["Victor Moses","MID",80],["Ahmed Musa","FWD",80],["Peter Odemwingie","FWD",80],["Emmanuel Emenike","FWD",79]]},
{t:"Nigeria",y:2018,f:"🇳🇬",p:[["Francis Uzoho","GK",76],["Leon Balogun","DEF",78],["William Troost-Ekong","DEF",80],["Bryan Idowu","DEF",76],["Victor Moses","MID",81],["Wilfred Ndidi","MID",82],["John Obi Mikel","MID",80],["Oghenekaro Etebo","MID",78],["Alex Iwobi","MID",79],["Ahmed Musa","FWD",82],["Odion Ighalo","FWD",79],["Kelechi Iheanacho","FWD",79]]},
// ---- Senegal → 3 (only three World Cups played)
{t:"Senegal",y:2018,f:"🇸🇳",p:[["Khadim N'Diaye","GK",77],["Kalidou Koulibaly","DEF",84],["Salif Sané","DEF",78],["Youssouf Sabaly","DEF",78],["Moussa Wagué","DEF",76],["Idrissa Gueye","MID",83],["Alfred N'Diaye","MID",77],["Badou Ndiaye","MID",78],["Ismaïla Sarr","FWD",80],["Sadio Mané","FWD",86],["M'Baye Niang","FWD",80],["Moussa Konaté","FWD",77]]},
{t:"Senegal",y:2022,f:"🇸🇳",p:[["Édouard Mendy","GK",84],["Kalidou Koulibaly","DEF",86],["Abdou Diallo","DEF",80],["Ismail Jakobs","DEF",77],["Youssouf Sabaly","DEF",78],["Idrissa Gueye","MID",84],["Nampalys Mendy","MID",78],["Pathé Ciss","MID",76],["Krépin Diatta","FWD",78],["Ismaïla Sarr","FWD",82],["Boulaye Dia","FWD",80],["Iliman Ndiaye","FWD",78]]},
// ---- Morocco → 4
{t:"Morocco",y:1986,f:"🇲🇦",p:[["Badou Zaki","GK",84],["Abdelmajid Lamriss","DEF",76],["Mustapha El Biyaz","DEF",76],["Noureddine Bouyahyaoui","DEF",76],["Abdelmajid Dolmy","MID",80],["Mohamed Timoumi","MID",85],["Aziz Bouderbala","MID",84],["Mustapha El Haddaoui","MID",79],["Abderrazak Khairi","FWD",80],["Abdelkrim Merry Krimau","FWD",81],["Mustapha Merry","FWD",76]]},
{t:"Morocco",y:1998,f:"🇲🇦",p:[["Driss Benzekri","GK",78],["Noureddine Naybet","DEF",83],["Abdelilah Saber","DEF",77],["Youssef Rossi","DEF",77],["Tahar El Khalej","DEF",79],["Saïd Chiba","MID",77],["Mustapha Hadji","MID",85],["Youssef Chippo","MID",81],["Salaheddine Bassir","FWD",81],["Abdeljalil Hadda","FWD",80],["Ali El Khattabi","FWD",76]]},
{t:"Morocco",y:2018,f:"🇲🇦",p:[["Munir El Kajoui","GK",78],["Achraf Hakimi","DEF",79],["Medhi Benatia","DEF",83],["Romain Saïss","DEF",80],["Manuel Da Costa","DEF",77],["Nabil Dirar","MID",78],["Karim El Ahmadi","MID",79],["Younès Belhanda","MID",80],["Hakim Ziyech","FWD",84],["Khalid Boutaïb","FWD",77],["Youssef En-Nesyri","FWD",78],["Nordin Amrabat","FWD",80]]},
// ---- Ghana → 4
{t:"Ghana",y:2006,f:"🇬🇭",p:[["Richard Kingson","GK",80],["John Pantsil","DEF",78],["John Mensah","DEF",80],["Shilla Illiasu","DEF",77],["Emmanuel Pappoe","DEF",76],["Michael Essien","MID",87],["Stephen Appiah","MID",85],["Sulley Muntari","MID",81],["Haminu Draman","FWD",77],["Asamoah Gyan","FWD",82],["Matthew Amoah","FWD",78],["Razak Pimpong","FWD",76]]},
{t:"Ghana",y:2014,f:"🇬🇭",p:[["Fatau Dauda","GK",76],["Harrison Afful","DEF",77],["John Boye","DEF",77],["Jonathan Mensah","DEF",78],["Daniel Opare","DEF",76],["Michael Essien","MID",81],["Sulley Muntari","MID",81],["Kevin-Prince Boateng","MID",81],["Mubarak Wakaso","MID",78],["André Ayew","MID",82],["Asamoah Gyan","FWD",84],["Jordan Ayew","FWD",79]]},
{t:"Ghana",y:2022,f:"🇬🇭",p:[["Lawrence Ati-Zigi","GK",77],["Daniel Amartey","DEF",78],["Mohammed Salisu","DEF",79],["Alexander Djiku","DEF",78],["Baba Rahman","DEF",77],["Tariq Lamptey","DEF",78],["Thomas Partey","MID",84],["Salis Abdul Samed","MID",77],["Mohammed Kudus","MID",83],["André Ayew","FWD",79],["Jordan Ayew","FWD",79],["Iñaki Williams","FWD",80],["Antoine Semenyo","FWD",77]]}
];
