// 21 squads added in v2 — same shape as the originals: {t, y, f, p:[[name,pos,rating]]}
// Ratings are unofficial, descriptive interpretations (70–99), consistent with v1 scale.
export const NEW_SQUADS = [
{t:"Uruguay",y:1950,f:"🇺🇾",p:[["Roque Máspoli","GK",86],["Matías González","DEF",80],["Eusebio Tejera","DEF",80],["Schubert Gambetta","DEF",81],["Víctor Rodríguez Andrade","MID",85],["Obdulio Varela","MID",91],["Julio Pérez","MID",83],["Alcides Ghiggia","FWD",90],["Juan Alberto Schiaffino","FWD",93],["Óscar Míguez","FWD",87],["Rubén Morán","FWD",79]]},
{t:"West Germany",y:1954,f:"🇩🇪",p:[["Toni Turek","GK",87],["Jupp Posipal","DEF",82],["Werner Kohlmeyer","DEF",81],["Werner Liebrich","DEF",85],["Horst Eckel","MID",84],["Karl Mai","MID",81],["Fritz Walter","MID",92],["Max Morlock","FWD",88],["Helmut Rahn","FWD",91],["Ottmar Walter","FWD",84],["Hans Schäfer","FWD",86]]},
{t:"Brazil",y:1962,f:"🇧🇷",p:[["Gilmar","GK",86],["Djalma Santos","DEF",90],["Mauro Ramos","DEF",84],["Zózimo","DEF",82],["Nilton Santos","DEF",89],["Zito","MID",85],["Didi","MID",91],["Zagallo","MID",86],["Garrincha","FWD",97],["Vavá","FWD",88],["Amarildo","FWD",84],["Pelé","FWD",93]]},
{t:"Portugal",y:1966,f:"🇵🇹",p:[["José Pereira","GK",80],["Morais","DEF",79],["Alexandre Baptista","DEF",80],["Vicente","DEF",81],["Hilário","DEF",80],["Jaime Graça","MID",83],["Mário Coluna","MID",89],["José Augusto","FWD",85],["Eusébio","FWD",96],["José Torres","FWD",86],["António Simões","FWD",85]]},
{t:"Soviet Union",y:1966,f:"🇷🇺",p:[["Lev Yashin","GK",95],["Albert Shesternyov","DEF",87],["Murtaz Khurtsilava","DEF",82],["Vasili Danilov","DEF",79],["Yozhef Sabo","MID",82],["Valery Voronin","MID",86],["Galimzyan Khusainov","FWD",83],["Igor Chislenko","FWD",86],["Anatoly Banishevsky","FWD",83],["Eduard Malofeyev","FWD",82],["Valery Porkujan","FWD",81]]},
{t:"Italy",y:1970,f:"🇮🇹",p:[["Enrico Albertosi","GK",85],["Tarcisio Burgnich","DEF",88],["Giacinto Facchetti","DEF",92],["Roberto Rosato","DEF",83],["Pierluigi Cera","DEF",82],["Mario Bertini","MID",81],["Sandro Mazzola","MID",91],["Giancarlo De Sisti","MID",84],["Gianni Rivera","MID",92],["Angelo Domenghini","FWD",83],["Luigi Riva","FWD",93]]},
{t:"Netherlands",y:1978,f:"🇳🇱",p:[["Jan Jongbloed","GK",76],["Wim Suurbier","DEF",82],["Ruud Krol","DEF",91],["Ernie Brandts","DEF",80],["Jan Poortvliet","DEF",78],["Wim Jansen","MID",83],["Johan Neeskens","MID",91],["Arie Haan","MID",87],["Willy van de Kerkhof","MID",82],["René van de Kerkhof","FWD",83],["Rob Rensenbrink","FWD",90],["Johnny Rep","FWD",86]]},
{t:"France",y:1982,f:"🇫🇷",p:[["Jean-Luc Ettori","GK",78],["Manuel Amoros","DEF",85],["Marius Trésor","DEF",89],["Gérard Janvion","DEF",80],["Maxime Bossis","DEF",84],["Jean Tigana","MID",89],["Alain Giresse","MID",90],["Bernard Genghini","MID",83],["Michel Platini","MID",96],["Dominique Rocheteau","FWD",85],["Didier Six","FWD",82]]},
{t:"Poland",y:1982,f:"🇵🇱",p:[["Józef Młynarczyk","GK",84],["Władysław Żmuda","DEF",84],["Stefan Majewski","DEF",80],["Paweł Janas","DEF",81],["Marek Dziuba","DEF",78],["Waldemar Matysik","MID",80],["Janusz Kupcewicz","MID",81],["Andrzej Buncol","MID",82],["Zbigniew Boniek","MID",92],["Grzegorz Lato","FWD",87],["Włodzimierz Smolarek","FWD",83]]},
{t:"Denmark",y:1986,f:"🇩🇰",p:[["Troels Rasmussen","GK",80],["John Sivebæk","DEF",81],["Morten Olsen","DEF",88],["Ivan Nielsen","DEF",81],["Søren Busk","DEF",80],["Søren Lerby","MID",87],["Jens Jørn Bertelsen","MID",80],["Frank Arnesen","MID",86],["Jesper Olsen","MID",84],["Michael Laudrup","FWD",92],["Preben Elkjær","FWD",91]]},
{t:"Belgium",y:1986,f:"🇧🇪",p:[["Jean-Marie Pfaff","GK",89],["Eric Gerets","DEF",86],["Michel Renquin","DEF",80],["Stéphane Demol","DEF",80],["Georges Grün","DEF",81],["Patrick Vervoort","DEF",79],["Enzo Scifo","MID",89],["Franky Vercauteren","MID",84],["Jan Ceulemans","FWD",89],["Nico Claesen","FWD",83],["Daniel Veyt","FWD",79]]},
{t:"Argentina",y:1990,f:"🇦🇷",p:[["Sergio Goycochea","GK",87],["Oscar Ruggeri","DEF",88],["Juan Simón","DEF",80],["José Serrizuela","DEF",79],["Julio Olarticoechea","DEF",80],["Néstor Lorenzo","DEF",78],["José Basualdo","MID",80],["Ricardo Giusti","MID",81],["Jorge Burruchaga","MID",85],["Diego Maradona","MID",93],["Claudio Caniggia","FWD",88],["Gustavo Dezotti","FWD",77]]},
{t:"Italy",y:1994,f:"🇮🇹",p:[["Gianluca Pagliuca","GK",87],["Franco Baresi","DEF",92],["Paolo Maldini","DEF",92],["Alessandro Costacurta","DEF",87],["Roberto Mussi","DEF",79],["Antonio Benarrivo","DEF",80],["Demetrio Albertini","MID",86],["Dino Baggio","MID",84],["Roberto Donadoni","MID",85],["Nicola Berti","MID",82],["Roberto Baggio","FWD",95],["Giuseppe Signori","FWD",86],["Daniele Massaro","FWD",83]]},
{t:"Sweden",y:1994,f:"🇸🇪",p:[["Thomas Ravelli","GK",86],["Roland Nilsson","DEF",84],["Patrik Andersson","DEF",84],["Joachim Björklund","DEF",81],["Roger Ljung","DEF",78],["Stefan Schwarz","MID",84],["Jonas Thern","MID",85],["Klas Ingesson","MID",81],["Tomas Brolin","FWD",89],["Martin Dahlin","FWD",86],["Kennet Andersson","FWD",87],["Henrik Larsson","FWD",82]]},
{t:"Nigeria",y:1994,f:"🇳🇬",p:[["Peter Rufai","GK",83],["Augustine Eguavoen","DEF",79],["Stephen Keshi","DEF",83],["Uche Okechukwu","DEF",82],["Ben Iroha","DEF",78],["Sunday Oliseh","MID",84],["Jay-Jay Okocha","MID",88],["Finidi George","MID",85],["Emmanuel Amunike","FWD",84],["Daniel Amokachi","FWD",85],["Rashidi Yekini","FWD",88],["Samson Siasia","FWD",80]]},
{t:"Croatia",y:1998,f:"🇭🇷",p:[["Dražen Ladić","GK",82],["Igor Štimac","DEF",84],["Slaven Bilić","DEF",85],["Dario Šimić","DEF",82],["Robert Jarni","DEF",84],["Zvonimir Soldo","MID",81],["Aljoša Asanović","MID",84],["Robert Prosinečki","MID",88],["Zvonimir Boban","MID",90],["Mario Stanić","FWD",81],["Davor Šuker","FWD",92],["Goran Vlaović","FWD",81]]},
{t:"Türkiye",y:2002,f:"🇹🇷",p:[["Rüştü Reçber","GK",88],["Alpay Özalan","DEF",84],["Bülent Korkmaz","DEF",83],["Fatih Akyel","DEF",79],["Hakan Ünsal","DEF",78],["Ergün Penbe","DEF",78],["Tugay Kerimoğlu","MID",84],["Emre Belözoğlu","MID",83],["Yıldıray Baştürk","MID",85],["Hasan Şaş","MID",83],["Ümit Davala","MID",80],["Hakan Şükür","FWD",86],["İlhan Mansız","FWD",82]]},
{t:"Brazil",y:2006,f:"🇧🇷",p:[["Dida","GK",87],["Cafu","DEF",88],["Lúcio","DEF",89],["Juan","DEF",84],["Roberto Carlos","DEF",89],["Emerson","MID",85],["Zé Roberto","MID",85],["Kaká","MID",93],["Ronaldinho","MID",95],["Adriano","FWD",88],["Ronaldo","FWD",90],["Robinho","FWD",85]]},
{t:"Germany",y:2010,f:"🇩🇪",p:[["Manuel Neuer","GK",89],["Philipp Lahm","DEF",90],["Per Mertesacker","DEF",84],["Arne Friedrich","DEF",81],["Jérôme Boateng","DEF",83],["Bastian Schweinsteiger","MID",89],["Sami Khedira","MID",84],["Mesut Özil","MID",88],["Thomas Müller","FWD",88],["Lukas Podolski","FWD",85],["Miroslav Klose","FWD",88],["Cacau","FWD",79]]},
{t:"Colombia",y:2014,f:"🇨🇴",p:[["David Ospina","GK",84],["Juan Camilo Zúñiga","DEF",82],["Mario Yepes","DEF",82],["Cristián Zapata","DEF",81],["Pablo Armero","DEF",80],["Carlos Sánchez","MID",82],["Abel Aguilar","MID",80],["Juan Guillermo Cuadrado","MID",86],["James Rodríguez","MID",91],["Juan Fernando Quintero","MID",80],["Teófilo Gutiérrez","FWD",82],["Jackson Martínez","FWD",84]]},
{t:"France",y:2022,f:"🇫🇷",p:[["Hugo Lloris","GK",86],["Jules Koundé","DEF",85],["Raphaël Varane","DEF",86],["Dayot Upamecano","DEF",83],["Theo Hernandez","DEF",85],["Aurélien Tchouaméni","MID",86],["Adrien Rabiot","MID",84],["Antoine Griezmann","MID",91],["Ousmane Dembélé","FWD",85],["Kylian Mbappé","FWD",96],["Olivier Giroud","FWD",85],["Randal Kolo Muani","FWD",81]]}
];

// opponent pool additions for v2 (name, flag, rating)
export const NEW_OPP = [
["Iran","🇮🇷",79],["Saudi Arabia","🇸🇦",76],["Egypt","🇪🇬",80],["Peru","🇵🇪",81],
["Canada","🇨🇦",79],["Algeria","🇩🇿",82],["Norway","🇳🇴",81],["Greece","🇬🇷",80]
];
