// 20 squads added in v3 — cult heroes, giant-killers and the near-immortals.
// Same shape as the originals: {t, y, f, p:[[name,pos,rating]]}
export const NEW_SQUADS_V3 = [
{t:"Austria",y:1954,f:"🇦🇹",p:[["Kurt Schmied","GK",81],["Gerhard Hanappi","DEF",86],["Ernst Happel","DEF",85],["Karl Stotz","DEF",78],["Ernst Ocwirk","MID",89],["Karl Koller","MID",82],["Walter Schleger","MID",78],["Robert Körner","FWD",80],["Alfred Körner","FWD",82],["Erich Probst","FWD",85],["Theodor Wagner","FWD",84]]},
{t:"Sweden",y:1958,f:"🇸🇪",p:[["Kalle Svensson","GK",84],["Orvar Bergmark","DEF",84],["Sven Axbom","DEF",80],["Bengt Gustavsson","DEF",82],["Sigge Parling","MID",81],["Nils Liedholm","MID",91],["Gunnar Gren","MID",89],["Kurt Hamrin","FWD",90],["Agne Simonsson","FWD",85],["Lennart Skoglund","FWD",86],["Henry Källgren","FWD",76]]},
{t:"Chile",y:1962,f:"🇨🇱",p:[["Misael Escuti","GK",82],["Luis Eyzaguirre","DEF",83],["Sergio Navarro","DEF",79],["Raúl Sánchez","DEF",80],["Carlos Contreras","DEF",78],["Eladio Rojas","MID",84],["Jorge Toro","MID",85],["Jaime Ramírez","FWD",83],["Leonel Sánchez","FWD",88],["Honorino Landa","FWD",80],["Armando Tobar","FWD",79]]},
{t:"Hungary",y:1966,f:"🇭🇺",p:[["József Gelei","GK",79],["Benő Káposzta","DEF",77],["Sándor Mátrai","DEF",81],["Kálmán Mészöly","DEF",86],["Ferenc Sipos","DEF",81],["Gyula Rákosi","MID",79],["István Nagy","MID",77],["Flórián Albert","FWD",93],["Ferenc Bene","FWD",88],["János Farkas","FWD",84],["Máté Fenyvesi","FWD",81]]},
{t:"Peru",y:1970,f:"🇵🇪",p:[["Luis Rubiños","GK",79],["Eloy Campos","DEF",78],["Héctor Chumpitaz","DEF",88],["Orlando de la Torre","DEF",77],["Nicolás Fuentes","DEF",79],["Ramón Mifflin","MID",83],["Roberto Challe","MID",84],["Teófilo Cubillas","MID",91],["Julio Baylón","FWD",80],["Pedro Pablo León","FWD",81],["Hugo Sotil","FWD",85],["Alberto Gallardo","FWD",82]]},
{t:"Scotland",y:1974,f:"🏴󠁧󠁢󠁳󠁣󠁴󠁿",p:[["David Harvey","GK",82],["Sandy Jardine","DEF",83],["Danny McGrain","DEF",85],["Jim Holton","DEF",80],["Martin Buchan","DEF",82],["Billy Bremner","MID",88],["Davie Hay","MID",83],["Peter Lorimer","FWD",84],["Willie Morgan","FWD",80],["Joe Jordan","FWD",84],["Kenny Dalglish","FWD",87],["Denis Law","FWD",86]]},
{t:"Austria",y:1978,f:"🇦🇹",p:[["Friedrich Koncilia","GK",84],["Robert Sara","DEF",80],["Erich Obermayer","DEF",79],["Bruno Pezzey","DEF",86],["Heribert Weber","DEF",79],["Josef Hickersberger","MID",80],["Herbert Prohaska","MID",87],["Kurt Jara","MID",82],["Wilhelm Kreuz","MID",80],["Hans Krankl","FWD",90],["Walter Schachner","FWD",82]]},
{t:"Algeria",y:1982,f:"🇩🇿",p:[["Mehdi Cerbah","GK",80],["Chaabane Merzekane","DEF",80],["Mahmoud Guendouz","DEF",79],["Noureddine Kourichi","DEF",79],["Faouzi Mansouri","DEF",78],["Ali Fergani","MID",83],["Mustapha Dahleb","MID",86],["Lakhdar Belloumi","MID",87],["Djamel Zidane","MID",80],["Salah Assad","FWD",84],["Rabah Madjer","FWD",85],["Tedj Bensaoula","FWD",81]]},
{t:"Northern Ireland",y:1982,f:"🇬🇧",p:[["Pat Jennings","GK",90],["Jimmy Nicholl","DEF",80],["Mal Donaghy","DEF",81],["Chris Nicholl","DEF",80],["John McClelland","DEF",80],["David McCreery","MID",79],["Martin O'Neill","MID",84],["Sammy McIlroy","MID",83],["Gerry Armstrong","FWD",83],["Billy Hamilton","FWD",80],["Norman Whiteside","FWD",82]]},
{t:"Mexico",y:1986,f:"🇲🇽",p:[["Pablo Larios","GK",81],["Rafael Amador","DEF",77],["Fernando Quirarte","DEF",81],["Félix Cruz","DEF",78],["Raúl Servín","DEF",78],["Tomás Boy","MID",83],["Manuel Negrete","MID",84],["Javier Aguirre","MID",79],["Miguel España","MID",78],["Hugo Sánchez","FWD",91],["Luis Flores","FWD",81],["Carlos Hermosillo","FWD",79]]},
{t:"Soviet Union",y:1986,f:"🇷🇺",p:[["Rinat Dasayev","GK",90],["Anatoliy Demyanenko","DEF",85],["Oleg Kuznetsov","DEF",84],["Vladimir Bessonov","DEF",83],["Vasyl Rats","MID",84],["Pavlo Yakovenko","MID",82],["Ivan Yaremchuk","MID",82],["Serhiy Aleinikov","MID",83],["Oleksandr Zavarov","MID",88],["Igor Belanov","FWD",89],["Oleg Blokhin","FWD",86]]},
{t:"Ireland",y:1990,f:"🇮🇪",p:[["Packie Bonner","GK",84],["Chris Morris","DEF",79],["Mick McCarthy","DEF",82],["Kevin Moran","DEF",81],["Steve Staunton","DEF",82],["Paul McGrath","DEF",88],["Ray Houghton","MID",84],["Andy Townsend","MID",82],["Kevin Sheedy","MID",83],["John Aldridge","FWD",84],["Niall Quinn","FWD",81],["Tony Cascarino","FWD",79]]},
{t:"Saudi Arabia",y:1994,f:"🇸🇦",p:[["Mohamed Al-Deayea","GK",84],["Mohammed Al-Khilaiwi","DEF",78],["Ahmed Madani","DEF",77],["Abdullah Zubromawi","DEF",76],["Fuad Anwar","MID",81],["Khalid Al-Muwallid","MID",80],["Fahad Al-Bishi","MID",80],["Saeed Al-Owairan","FWD",85],["Sami Al-Jaber","FWD",84],["Majed Abdullah","FWD",83],["Fahad Al-Ghesheyan","FWD",78]]},
{t:"Denmark",y:1998,f:"🇩🇰",p:[["Peter Schmeichel","GK",93],["Thomas Helveg","DEF",84],["Jes Høgh","DEF",81],["Marc Rieper","DEF",82],["Jan Heintze","DEF",80],["Søren Colding","DEF",78],["Allan Nielsen","MID",81],["Martin Jørgensen","MID",82],["Michael Laudrup","MID",92],["Brian Laudrup","FWD",91],["Ebbe Sand","FWD",83],["Peter Møller","FWD",79]]},
{t:"United States",y:2002,f:"🇺🇸",p:[["Brad Friedel","GK",86],["Tony Sanneh","DEF",80],["Eddie Pope","DEF",81],["Gregg Berhalter","DEF",78],["Frankie Hejduk","DEF",79],["Pablo Mastroeni","MID",80],["John O'Brien","MID",81],["Claudio Reyna","MID",84],["DaMarcus Beasley","MID",80],["Clint Mathis","MID",79],["Landon Donovan","FWD",84],["Brian McBride","FWD",82]]},
{t:"Argentina",y:2006,f:"🇦🇷",p:[["Roberto Abbondanzieri","GK",82],["Roberto Ayala","DEF",87],["Gabriel Heinze","DEF",84],["Juan Pablo Sorín","DEF",83],["Nicolás Burdisso","DEF",80],["Lionel Scaloni","DEF",78],["Javier Mascherano","MID",86],["Esteban Cambiasso","MID",85],["Maxi Rodríguez","MID",84],["Juan Román Riquelme","MID",90],["Javier Saviola","FWD",84],["Hernán Crespo","FWD",88],["Lionel Messi","FWD",86],["Carlos Tevez","FWD",87]]},
{t:"Australia",y:2006,f:"🇦🇺",p:[["Mark Schwarzer","GK",85],["Lucas Neill","DEF",84],["Craig Moore","DEF",80],["Scott Chipperfield","DEF",80],["Brett Emerton","MID",82],["Vince Grella","MID",81],["Jason Culina","MID",79],["Tim Cahill","MID",85],["Mark Bresciano","MID",82],["Harry Kewell","FWD",86],["Mark Viduka","FWD",85],["John Aloisi","FWD",80]]},
{t:"Ghana",y:2010,f:"🇬🇭",p:[["Richard Kingson","GK",79],["John Pantsil","DEF",79],["John Mensah","DEF",82],["Isaac Vorsah","DEF",79],["Hans Sarpei","DEF",78],["Anthony Annan","MID",80],["Kwadwo Asamoah","MID",83],["Kevin-Prince Boateng","MID",83],["André Ayew","MID",82],["Sulley Muntari","MID",83],["Asamoah Gyan","FWD",86],["Matthew Amoah","FWD",77]]},
{t:"Costa Rica",y:2014,f:"🇨🇷",p:[["Keylor Navas","GK",89],["Cristian Gamboa","DEF",79],["Giancarlo González","DEF",81],["Óscar Duarte","DEF",80],["Michael Umaña","DEF",78],["Júnior Díaz","DEF",78],["Celso Borges","MID",82],["Yeltsin Tejeda","MID",79],["Christian Bolaños","MID",81],["Bryan Ruiz","FWD",84],["Joel Campbell","FWD",82],["Marco Ureña","FWD",78]]},
{t:"Netherlands",y:2014,f:"🇳🇱",p:[["Jasper Cillessen","GK",82],["Ron Vlaar","DEF",81],["Stefan de Vrij","DEF",83],["Bruno Martins Indi","DEF",79],["Daley Blind","DEF",83],["Daryl Janmaat","DEF",80],["Nigel de Jong","MID",83],["Georginio Wijnaldum","MID",83],["Wesley Sneijder","MID",87],["Dirk Kuyt","FWD",82],["Arjen Robben","FWD",91],["Robin van Persie","FWD",90],["Memphis Depay","FWD",80],["Klaas-Jan Huntelaar","FWD",82]]},
{t:"Brazil",y:2018,f:"🇧🇷",p:[["Alisson","GK",89],["Fagner","DEF",80],["Thiago Silva","DEF",89],["Miranda","DEF",86],["Marcelo","DEF",88],["Filipe Luís","DEF",83],["Casemiro","MID",88],["Paulinho","MID",83],["Renato Augusto","MID",80],["Philippe Coutinho","MID",89],["Willian","FWD",84],["Neymar","FWD",94],["Gabriel Jesus","FWD",83],["Roberto Firmino","FWD",86]]},
{t:"Japan",y:2022,f:"🇯🇵",p:[["Shūichi Gonda","GK",80],["Miki Yamane","DEF",78],["Maya Yoshida","DEF",81],["Kō Itakura","DEF",81],["Yuto Nagatomo","DEF",79],["Hiroki Ito","DEF",78],["Wataru Endo","MID",84],["Hidemasa Morita","MID",81],["Daichi Kamada","MID",84],["Junya Ito","FWD",83],["Ritsu Doan","FWD",82],["Takefusa Kubo","FWD",82],["Kaoru Mitoma","FWD",84],["Daizen Maeda","FWD",78]]}
];
