// 2026 World Cup — the trophy contenders, projected current-star squads.
// (Final 26-man rosters are announced June 2026; these are best-confidence
//  squads of each nation's current core. Same shape: {t,y,f,p:[[name,pos,rating]]})
export const NEW_SQUADS_V5 = [
{t:"Argentina",y:2026,f:"🇦🇷",p:[["Emiliano Martínez","GK",89],["Nahuel Molina","DEF",82],["Cristian Romero","DEF",86],["Nicolás Otamendi","DEF",82],["Lisandro Martínez","DEF",84],["Nicolás Tagliafico","DEF",82],["Rodrigo De Paul","MID",85],["Enzo Fernández","MID",86],["Alexis Mac Allister","MID",87],["Giovani Lo Celso","MID",82],["Lionel Messi","FWD",92],["Julián Álvarez","FWD",89],["Lautaro Martínez","FWD",88],["Nico Paz","MID",81]]},
{t:"France",y:2026,f:"🇫🇷",p:[["Mike Maignan","GK",87],["Jules Koundé","DEF",85],["William Saliba","DEF",87],["Dayot Upamecano","DEF",85],["Ibrahima Konaté","DEF",84],["Theo Hernández","DEF",85],["Aurélien Tchouaméni","MID",87],["Eduardo Camavinga","MID",85],["Adrien Rabiot","MID",83],["Kylian Mbappé","FWD",94],["Ousmane Dembélé","FWD",87],["Michael Olise","FWD",85],["Marcus Thuram","FWD",84]]},
{t:"Brazil",y:2026,f:"🇧🇷",p:[["Alisson","GK",89],["Danilo","DEF",81],["Marquinhos","DEF",86],["Éder Militão","DEF",85],["Gabriel Magalhães","DEF",85],["Wendell","DEF",79],["Casemiro","MID",83],["Bruno Guimarães","MID",86],["Lucas Paquetá","MID",84],["Vinícius Júnior","FWD",93],["Rodrygo","FWD",88],["Raphinha","FWD",87],["Endrick","FWD",83]]},
{t:"England",y:2026,f:"🏴󠁧󠁢󠁥󠁮󠁧󠁿",p:[["Jordan Pickford","GK",84],["Kyle Walker","DEF",82],["John Stones","DEF",84],["Marc Guéhi","DEF",83],["Kieran Trippier","DEF",81],["Declan Rice","MID",88],["Jude Bellingham","MID",91],["Phil Foden","MID",88],["Cole Palmer","MID",87],["Harry Kane","FWD",90],["Bukayo Saka","FWD",88],["Marcus Rashford","FWD",84],["Anthony Gordon","FWD",82]]},
{t:"Spain",y:2026,f:"🇪🇸",p:[["Unai Simón","GK",85],["Dani Carvajal","DEF",85],["Pau Cubarsí","DEF",83],["Aymeric Laporte","DEF",84],["Robin Le Normand","DEF",83],["Marc Cucurella","DEF",83],["Rodri","MID",92],["Pedri","MID",89],["Fabián Ruiz","MID",84],["Dani Olmo","MID",85],["Lamine Yamal","FWD",90],["Nico Williams","FWD",86],["Álvaro Morata","FWD",83]]},
{t:"Portugal",y:2026,f:"🇵🇹",p:[["Diogo Costa","GK",85],["João Cancelo","DEF",85],["Rúben Dias","DEF",87],["Gonçalo Inácio","DEF",82],["Nuno Mendes","DEF",85],["Vitinha","MID",86],["Bruno Fernandes","MID",88],["Bernardo Silva","MID",88],["João Neves","MID",84],["Cristiano Ronaldo","FWD",88],["Rafael Leão","FWD",86],["Pedro Neto","FWD",83],["João Félix","FWD",83]]},
{t:"Germany",y:2026,f:"🇩🇪",p:[["Marc-André ter Stegen","GK",87],["Joshua Kimmich","DEF",87],["Antonio Rüdiger","DEF",87],["Jonathan Tah","DEF",84],["Nico Schlotterbeck","DEF",84],["Maximilian Mittelstädt","DEF",81],["Robert Andrich","MID",81],["Jamal Musiala","MID",90],["Florian Wirtz","MID",89],["Kai Havertz","FWD",85],["Leroy Sané","FWD",84],["Serge Gnabry","FWD",83],["Niclas Füllkrug","FWD",82]]},
{t:"Netherlands",y:2026,f:"🇳🇱",p:[["Bart Verbruggen","GK",82],["Denzel Dumfries","DEF",83],["Virgil van Dijk","DEF",88],["Matthijs de Ligt","DEF",85],["Jurriën Timber","DEF",83],["Nathan Aké","DEF",83],["Frenkie de Jong","MID",87],["Tijjani Reijnders","MID",84],["Ryan Gravenberch","MID",84],["Xavi Simons","MID",85],["Cody Gakpo","FWD",85],["Memphis Depay","FWD",83],["Donyell Malen","FWD",81]]},
{t:"Belgium",y:2026,f:"🇧🇪",p:[["Thibaut Courtois","GK",90],["Timothy Castagne","DEF",81],["Wout Faes","DEF",80],["Zeno Debast","DEF",80],["Arthur Theate","DEF",81],["Maxim De Cuyper","DEF",79],["Youri Tielemans","MID",84],["Amadou Onana","MID",83],["Kevin De Bruyne","MID",90],["Jérémy Doku","FWD",85],["Romelu Lukaku","FWD",86],["Leandro Trossard","FWD",83],["Loïs Openda","FWD",84]]},
{t:"Croatia",y:2026,f:"🇭🇷",p:[["Dominik Livaković","GK",84],["Josip Stanišić","DEF",81],["Joško Gvardiol","DEF",87],["Josip Šutalo","DEF",80],["Josip Juranović","DEF",80],["Borna Sosa","DEF",80],["Luka Modrić","MID",86],["Mateo Kovačić","MID",85],["Marcelo Brozović","MID",83],["Luka Sučić","MID",81],["Andrej Kramarić","FWD",82],["Ivan Perišić","FWD",82],["Ante Budimir","FWD",80]]},
{t:"Uruguay",y:2026,f:"🇺🇾",p:[["Sergio Rochet","GK",80],["Nahitan Nández","DEF",80],["Ronald Araújo","DEF",86],["José María Giménez","DEF",84],["Sebastián Cáceres","DEF",79],["Mathías Olivera","DEF",81],["Federico Valverde","MID",89],["Manuel Ugarte","MID",82],["Rodrigo Bentancur","MID",83],["Giorgian De Arrascaeta","MID",83],["Darwin Núñez","FWD",84],["Facundo Pellistri","FWD",80],["Maximiliano Araújo","FWD",79]]},
{t:"Morocco",y:2026,f:"🇲🇦",p:[["Yassine Bounou","GK",86],["Achraf Hakimi","DEF",87],["Nayef Aguerd","DEF",82],["Romain Saïss","DEF",80],["Noussair Mazraoui","DEF",83],["Sofyan Amrabat","MID",83],["Azzedine Ounahi","MID",81],["Bilal El Khannouss","MID",81],["Brahim Díaz","MID",84],["Hakim Ziyech","FWD",83],["Youssef En-Nesyri","FWD",82],["Amine Adli","FWD",80],["Eliesse Ben Seghir","FWD",80]]}
];
